// Where `packages/account`'s refresh token state machine meets rows.
//
// The rules are not restated here and must not be. `refresh` decides, in pure
// logic with 41 tests behind it, and this file only feeds it two rows and then
// writes down what it decided. The one rule worth repeating as a comment,
// because it is what the ordering of this file protects: REUSE IS AN ALARM AND
// EXPIRY IS HOUSEKEEPING, so a token that is both is reported as reuse.
//
// TWO ROWS, NOT EVERY ROW. `refresh` takes maps of tokens and families because
// it was written without a database in mind. It only ever looks up the presented
// token and that token's own family, so the maps built here hold one entry each.
// Loading every token in the table to satisfy a signature would be the kind of
// literal reading that turns a clean interface into an outage.
//
// AND THE WHOLE THING IS ONE TRANSACTION. Marking a token used and writing its
// successor are two writes that must not come apart: a crash between them either
// logs a real user out for nothing or leaves the old token valid, which is
// rotation quietly not happening.

import { and, eq, isNull } from 'drizzle-orm';
import { refresh } from '@transferchecker/account';
import type { Family, RefreshOutcome, TokenRecord } from '@transferchecker/account';
import { refreshTokens, tokenFamilies } from './schema/sessions';
import { hashSecret } from './secret';
import type { Database } from './database';

/**
 * What goes in the `id` column: the SHA-256 of the token, never the token.
 *
 * The account layer says of its own field that it may hold "the token itself, or
 * a hash of it", and leaves the choice to whoever owns storage. This is the
 * choice, and the reasoning behind the hash is in `secret.ts`, next to the
 * generator, because the confirmation link makes exactly the same one.
 */
export const hashToken = hashSecret;

export interface StartSession {
  readonly familyId: string;
  readonly orgId: string;
  readonly userId: string;
  /** The raw token. Only its hash is written. */
  readonly token: string;
  readonly now: number;
  readonly lifetimeMs: number;
  readonly deviceLabel?: string;
}

/** A fresh login: one family, one token. */
export async function startSession(db: Database, input: StartSession): Promise<void> {
  await db.transaction(async (tx) => {
    await tx.insert(tokenFamilies).values({
      id: input.familyId,
      orgId: input.orgId,
      userId: input.userId,
      createdAt: new Date(input.now),
      ...(input.deviceLabel === undefined ? {} : { deviceLabel: input.deviceLabel }),
    });
    await tx.insert(refreshTokens).values({
      id: hashToken(input.token),
      familyId: input.familyId,
      orgId: input.orgId,
      expiresAt: new Date(input.now + input.lifetimeMs),
      createdAt: new Date(input.now),
    });
  });
}

export interface RefreshInput {
  /** The raw token the client presented. */
  readonly presented: string;
  /** The raw successor, generated by the caller. Only its hash is written. */
  readonly successor: string;
  readonly now: number;
  readonly lifetimeMs: number;
}

/**
 * Exchanges a refresh token, or refuses and says why.
 *
 * Returns the account layer's own outcome unchanged, so a caller reads one
 * vocabulary whether the decision came from memory or from a table. On `reused`
 * the family has already been revoked by the time this returns: the alarm and
 * the response are in the same transaction, because a thief who is told "no" and
 * left holding a live family has lost nothing.
 */
export async function refreshSession(db: Database, input: RefreshInput): Promise<RefreshOutcome> {
  const presentedId = hashToken(input.presented);

  return db.transaction(async (tx) => {
    const [row] = await tx
      .select()
      .from(refreshTokens)
      .where(eq(refreshTokens.id, presentedId))
      .limit(1);

    // An unknown token is refused without touching anything. Note that this is
    // also what a token from a family whose rows were purged looks like, and
    // both answers are the same to the caller on purpose.
    if (row === undefined) return { ok: false, reason: 'unknown-token' };

    const [family] = await tx
      .select()
      .from(tokenFamilies)
      .where(eq(tokenFamilies.id, row.familyId))
      .limit(1);
    if (family === undefined) return { ok: false, reason: 'unknown-token' };

    const record: TokenRecord = {
      id: row.id,
      family: row.familyId,
      expiresAt: row.expiresAt.getTime(),
      ...(row.usedAt === null ? {} : { usedAt: row.usedAt.getTime() }),
    };
    const held: Family = {
      id: family.id,
      ...(family.revokedAt === null ? {} : { revokedAt: family.revokedAt.getTime() }),
    };

    const outcome = refresh({
      presented: presentedId,
      now: input.now,
      lifetimeMs: input.lifetimeMs,
      tokens: new Map([[presentedId, record]]),
      families: new Map([[held.id, held]]),
    });

    if (!outcome.ok) {
      if (outcome.revokeFamily !== undefined) {
        // The whole family, in the same transaction that refused the request.
        // Marking every token used rather than deleting them keeps the evidence
        // and makes a later presentation of any of them read as reuse again.
        await tx
          .update(tokenFamilies)
          .set({ revokedAt: new Date(input.now), revokedReason: 'reuse' })
          .where(eq(tokenFamilies.id, outcome.revokeFamily));
        await tx
          .update(refreshTokens)
          .set({ usedAt: new Date(input.now) })
          .where(
            and(eq(refreshTokens.familyId, outcome.revokeFamily), isNull(refreshTokens.usedAt)),
          );
      }
      return outcome;
    }

    await tx
      .update(refreshTokens)
      .set({ usedAt: new Date(input.now) })
      .where(eq(refreshTokens.id, presentedId));
    await tx.insert(refreshTokens).values({
      id: hashToken(input.successor),
      familyId: row.familyId,
      orgId: row.orgId,
      expiresAt: new Date(outcome.issue.expiresAt),
      createdAt: new Date(input.now),
    });
    return outcome;
  });
}

/** Ending a session deliberately, which is not a theft and is not recorded as one. */
export async function revokeFamily(
  db: Database,
  familyId: string,
  now: number,
  reason: 'signed-out' | 'password-changed' = 'signed-out',
): Promise<void> {
  await db.transaction(async (tx) => {
    await tx
      .update(tokenFamilies)
      .set({ revokedAt: new Date(now), revokedReason: reason })
      .where(and(eq(tokenFamilies.id, familyId), isNull(tokenFamilies.revokedAt)));
    await tx
      .update(refreshTokens)
      .set({ usedAt: new Date(now) })
      .where(and(eq(refreshTokens.familyId, familyId), isNull(refreshTokens.usedAt)));
  });
}
