// The shape of the real golden set, as a schema rather than as a convention.
//
// Tier 3 is three hundred photographs of real paper, and none of them exist
// yet. What exists is the RECEPTION: the format they arrive in, the checks they
// pass on arrival, and the truth they arrive with. Building that first is not
// ceremony. A corpus assembled without one is assembled twice, and the second
// time is after somebody has already photographed three hundred sheets.
//
// Four decisions live in this file, each with the failure it is written against.
//
// THE BYTES DO NOT LIVE IN THE REPOSITORY, their hashes do. A PGM is
// uncompressed, so the full set is about a gigabyte, and a gigabyte in git is a
// gigabyte in every clone forever. So the repository carries the index and the
// truth, which is what review is for, and the shots sit in a directory named by
// `TRANSFERCHECKER_GOLDEN_ROOT`. The SHA-256 is what makes that safe: a shot
// that is swapped, re-exported at a different quality or accidentally rotated
// no longer matches its hash, and the loader says so by name instead of quietly
// scoring a different photograph than the one the truth was read from.
//
// THE TRUTH IS READ BY PEOPLE, TWICE. The first run of the synthetic sweep
// failed on a corpus error and not an engine error, and that corpus was
// generated by code. A truth read off paper by one tired person at midnight is
// worse, and every disagreement it produces will be investigated as an engine
// defect. So `readBy` carries names and a real paper needs two of them.
//
// A PAPER NEEDS THREE SHOTS THAT DIFFER. Acceptance criterion 8 asks every
// paper for at least three captures at different angles and lighting, and
// criterion 12 asks the three to agree on the whole result and not on the score.
// A paper photographed three times from the same chair proves nothing, so the
// schema refuses it rather than letting it inflate the count.
//
// AND A PAPER NOBODY HAS READ YET IS A VALID DOCUMENT. `import-shot.ts` writes
// a truth file with every question marked `unread`, because the alternative is
// an invalid file that fails validation for weeks while the shots accumulate.
// An unread question is never scored and its paper never counts toward arming
// the accuracy gate.

import { z } from 'zod';

const SHA256 = z.string().regex(/^[0-9a-f]{64}$/, 'a SHA-256 as 64 lowercase hex characters');

const DATE = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'a date as YYYY-MM-DD');

const PAPER_ID = z
  .string()
  .regex(/^[a-z0-9][a-z0-9-]{2,47}$/, 'a directory name: lowercase, digits and hyphens');

/** A file the repository carries, bound to the manifest by its hash. */
const FileRefSchema = z.object({ sha256: SHA256, bytes: z.number().int().positive() });

/**
 * Where the pixels came from, which is the stratum the per environment floor of
 * acceptance criterion 14 is computed over.
 *
 * `flatbed` is tier 2 and shares this whole format on purpose: a scan at 300dpi
 * arrives as the same grey plane through the same reader, and the only thing
 * that differs is which stratum its accuracy is reported under. Building two
 * formats for that would be two formats to keep in step.
 */
export const SHOT_SOURCES = ['phone', 'flatbed', 'fixture'] as const;
export const SHOT_LIGHTING = [
  'daylight',
  'shade',
  'tungsten',
  'fluorescent',
  'mixed',
  'point-source',
] as const;
export const SHOT_ANGLES = ['flat', 'tilted', 'steep'] as const;

/**
 * The closed set of endings a shot may declare, which is `Rejection['kind']`
 * plus a grade. Written out rather than derived because this is a wire format:
 * a rejection cause that is renamed in the engine must not silently change the
 * meaning of a manifest a person wrote six months ago, and the type test in
 * `test/tier3.test.ts` fails the build when the two drift apart.
 */
export const REFUSALS = [
  'graded',
  'no_sheet',
  'code_unreadable',
  'code_too_small',
  'too_steep',
  'template_unknown',
  'not_this_geometry',
  'not_one_sheet',
  'rows_missing',
  'anchors_missing',
  'sheet_not_flat',
  'glare',
  'low_contrast',
] as const;

export const ShotSchema = z.object({
  /** Relative to the paper's `shots/` directory, and never an absolute path. */
  file: z.string().regex(/^[a-z0-9][a-z0-9.-]{2,63}\.pgm$/, 'a file name ending in .pgm'),
  sha256: SHA256,
  bytes: z.number().int().positive(),
  width: z.number().int().min(64),
  height: z.number().int().min(64),
  source: z.enum(SHOT_SOURCES),
  device: z.string().min(1).max(60),
  capturedAt: DATE,
  lighting: z.enum(SHOT_LIGHTING),
  angle: z.enum(SHOT_ANGLES),
  /**
   * What this shot is supposed to produce: a grade, or one named refusal.
   *
   * A shot taken to be refused is not a failure and never counts against the
   * refusal budget, which is acceptance criterion 14's adversarial stratum:
   * glare aimed into a shaded bubble, a curled sheet, two sheets in frame. The
   * cause is spelled out rather than left as a boolean because criterion 16
   * asks the reported cause to match the injected defect above 90 percent, and
   * that cannot be measured against "something should have gone wrong".
   */
  expect: z.enum(REFUSALS),
  why: z.string().min(1).max(160),
});

/**
 * The fields of a paper, without the rules that span them.
 *
 * The split exists because importing is incremental. A paper is one shot for as
 * long as it takes to import the second one, and a set that cannot be read back
 * in that state would make the importer unable to append to its own output.
 * `PaperShapeSchema` is what writes, `PaperSchema` is what a build reads.
 */
export const PaperShapeSchema = z.object({
  id: PAPER_ID,
  /** A fixture exercises this format and never counts toward the real set. */
  kind: z.enum(['real', 'fixture']),
  printer: z.string().min(1).max(60),
  /** What the print dialog actually did, since 'fit to page' is the common case. */
  printScale: z.number().min(0.5).max(1.5),
  pen: z.string().min(1).max(40),
  spec: FileRefSchema,
  truth: FileRefSchema,
  shots: z.array(ShotSchema).min(1).max(24),
  why: z.string().min(1).max(200),
});

export const PaperSchema = PaperShapeSchema.refine(
  (paper) => paper.kind !== 'real' || paper.shots.length >= 3,
  'a real paper needs at least three shots, since determinism cannot be measured on one',
).refine(
  (paper) =>
    paper.kind !== 'real' ||
    new Set(paper.shots.map((shot) => `${shot.lighting}/${shot.angle}`)).size >= 2,
  'the shots of a real paper must differ in lighting or angle, or they prove only that the camera did not move',
);

const manifestShape = {
  /** This file's own shape. Bumped when a field changes meaning, not when one is added. */
  format: z.literal(1),
  /**
   * The sheet version every paper here was printed at. A version 3 sheet is a
   * different piece of paper and the engine refuses it, so a set that mixes
   * them silently would report the refusals as an accuracy problem.
   */
  sheetVersion: z.literal(4),
  note: z.string().min(1),
};

/** What the importer reads back so it can append to a set that is still arriving. */
export const ManifestShapeSchema = z.object({
  ...manifestShape,
  papers: z.array(PaperShapeSchema),
});

/** And what a build reads, where every rule that spans fields applies. */
export const ManifestSchema = z
  .object({ ...manifestShape, papers: z.array(PaperSchema) })
  .refine(
    (manifest) => new Set(manifest.papers.map((paper) => paper.id)).size === manifest.papers.length,
    'two papers share an id, so one of them would be scored against the other truth',
  );

/**
 * One question as a person read it off the paper.
 *
 * The four judged kinds are the same four `truth.ts` derives for a synthetic
 * case, deliberately and not coincidentally: a tier 3 paper produces the same
 * `Expected` a tier 0 case does, so one scoring rule covers both and there is
 * never a second definition of what counts as a wrong answer.
 */
export const TruthEntrySchema = z.discriminatedUnion('kind', [
  z.object({
    question: z.number().int().min(1),
    kind: z.literal('answer'),
    symbol: z.string().min(1).max(2),
  }),
  z.object({ question: z.number().int().min(1), kind: z.literal('blank') }),
  z.object({
    question: z.number().int().min(1),
    kind: z.literal('flagged'),
    why: z.string().min(1).max(120),
  }),
  z.object({
    question: z.number().int().min(1),
    kind: z.literal('either'),
    symbol: z.string().min(1).max(2),
    why: z.string().min(1).max(120),
  }),
  /** Written by the importer, cleared by a person. Never scored. */
  z.object({ question: z.number().int().min(1), kind: z.literal('unread') }),
]);

export const TruthSchema = z
  .object({
    paper: PAPER_ID,
    /** The people who read this paper by eye. Two, for a real paper. */
    readBy: z.array(z.string().min(1).max(60)).min(1).max(4),
    readAt: DATE,
    /** What the identity grid says, as a person reads it, or null for an empty grid. */
    identity: z.string().max(12).nullable(),
    questions: z.array(TruthEntrySchema).min(1),
  })
  .refine(
    (truth) =>
      new Set(truth.questions.map((entry) => entry.question)).size === truth.questions.length,
    'a question is read twice, so which reading is the truth is undefined',
  );

export type FileRef = z.output<typeof FileRefSchema>;
export type Shot = z.output<typeof ShotSchema>;
export type PaperEntry = z.output<typeof PaperShapeSchema>;
export type Manifest = z.output<typeof ManifestShapeSchema>;
export type TruthEntry = z.output<typeof TruthEntrySchema>;
export type PaperTruth = z.output<typeof TruthSchema>;
